version: '3.1'
services:
  redpanda:
    command:
      # https://docs.redpanda.com/current/get-started/quick-start/
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --memory 1G
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.12
    container_name: redpanda
    volumes:
      - redpanda:/var/lib/redpanda/data
    ports:
      - '18081:18081' # Schema registry
      - '18082:18082' # Panda HTTP proxy
      - '9092:9092'   # Kafka API
      - '19644:9644'  # Prometheus and HTTP admin

  console:
    container_name: console
    image: docker.redpanda.com/redpandadata/console:v2.4.7
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8090:8080
    depends_on:
      - redpanda

  mongo:
    image: mongo:7-jammy
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: service
    volumes:
      - mongo:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - redpanda
    env_file:
      - .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29029
      - MONGODB_URI=mongodb://mongo:27017
      - LOG_FILE_PATH=/tmp/service.log

volumes:
  redpanda:
  mongo:
